// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilfetchApplicationRequest is returned when the fetchApplicationRequest is nil.
	ErrNilfetchApplicationRequest = errors.New("input fetchApplicationRequest is nil")

	// ErrfetchApplicationRequestApplicationIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrfetchApplicationRequestApplicationIDGTValidation = govaliderrors.ValidationError{Reason: "field ApplicationID must be greater than 0", Path: "fetchApplicationRequest.ApplicationID", Type: "gt"}

	// ErrfetchApplicationRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrfetchApplicationRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "fetchApplicationRequest.ApplicationID", Type: "required"}
)

func ValidatefetchApplicationRequest(t *fetchApplicationRequest) error {
	if t == nil {
		return ErrNilfetchApplicationRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ApplicationID > 0) {
		err := ErrfetchApplicationRequestApplicationIDGTValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.ApplicationID == 0 {
		err := ErrfetchApplicationRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*fetchApplicationRequest)(nil)

func (t *fetchApplicationRequest) Validate() error {
	return ValidatefetchApplicationRequest(t)
}
