// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"regexp"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilcreateMessageApplicationRequest is returned when the createMessageApplicationRequest is nil.
	ErrNilcreateMessageApplicationRequest = errors.New("input createMessageApplicationRequest is nil")

	// ErrcreateMessageApplicationRequestApplicationNameRequiredValidation is returned when the ApplicationName is required but not provided.
	ErrcreateMessageApplicationRequestApplicationNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationName is required", Path: "createMessageApplicationRequest.ApplicationName", Type: "required"}

	// ErrcreateMessageApplicationRequestRequestTypeCELValidation is the error returned when the CEL expression evaluation fails.
	ErrcreateMessageApplicationRequestRequestTypeCELValidation = govaliderrors.ValidationError{Reason: "field RequestType failed CEL validation: value.matches('^[1-4](,[1-4])*$')", Path: "createMessageApplicationRequest.RequestType", Type: "cel"}

	// ErrcreateMessageApplicationRequestRequestTypeRequiredValidation is returned when the RequestType is required but not provided.
	ErrcreateMessageApplicationRequestRequestTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestType is required", Path: "createMessageApplicationRequest.RequestType", Type: "required"}

	// ErrcreateMessageApplicationRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrcreateMessageApplicationRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "createMessageApplicationRequest.Status", Type: "required"}
)

func ValidatecreateMessageApplicationRequest(t *createMessageApplicationRequest) error {
	if t == nil {
		return ErrNilcreateMessageApplicationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationName == "" {
		err := ErrcreateMessageApplicationRequestApplicationNameRequiredValidation
		err.Value = t.ApplicationName
		errs = append(errs, err)
	}

	if !(regexp.MustCompile("^[1-4](,[1-4])*$").MatchString(t.RequestType)) {
		err := ErrcreateMessageApplicationRequestRequestTypeCELValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.RequestType == "" {
		err := ErrcreateMessageApplicationRequestRequestTypeRequiredValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrcreateMessageApplicationRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*createMessageApplicationRequest)(nil)

func (t *createMessageApplicationRequest) Validate() error {
	return ValidatecreateMessageApplicationRequest(t)
}
