// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNiltoggleApplicationStatusRequest is returned when the toggleApplicationStatusRequest is nil.
	ErrNiltoggleApplicationStatusRequest = errors.New("input toggleApplicationStatusRequest is nil")

	// ErrtoggleApplicationStatusRequestApplicationIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrtoggleApplicationStatusRequestApplicationIDGTValidation = govaliderrors.ValidationError{Reason: "field ApplicationID must be greater than 0", Path: "toggleApplicationStatusRequest.ApplicationID", Type: "gt"}

	// ErrtoggleApplicationStatusRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrtoggleApplicationStatusRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "toggleApplicationStatusRequest.ApplicationID", Type: "required"}
)

func ValidatetoggleApplicationStatusRequest(t *toggleApplicationStatusRequest) error {
	if t == nil {
		return ErrNiltoggleApplicationStatusRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ApplicationID > 0) {
		err := ErrtoggleApplicationStatusRequestApplicationIDGTValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.ApplicationID == 0 {
		err := ErrtoggleApplicationStatusRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*toggleApplicationStatusRequest)(nil)

func (t *toggleApplicationStatusRequest) Validate() error {
	return ValidatetoggleApplicationStatusRequest(t)
}
