// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"regexp"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilcreateMessageApplicationXMLRequest is returned when the createMessageApplicationXMLRequest is nil.
	ErrNilcreateMessageApplicationXMLRequest = errors.New("input createMessageApplicationXMLRequest is nil")

	// ErrcreateMessageApplicationXMLRequestApplicationNameRequiredValidation is returned when the ApplicationName is required but not provided.
	ErrcreateMessageApplicationXMLRequestApplicationNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationName is required", Path: "createMessageApplicationXMLRequest.ApplicationName", Type: "required"}

	// ErrcreateMessageApplicationXMLRequestRequestTypeCELValidation is the error returned when the CEL expression evaluation fails.
	ErrcreateMessageApplicationXMLRequestRequestTypeCELValidation = govaliderrors.ValidationError{Reason: "field RequestType failed CEL validation: value.matches('^[1-4](,[1-4])*$')", Path: "createMessageApplicationXMLRequest.RequestType", Type: "cel"}

	// ErrcreateMessageApplicationXMLRequestRequestTypeRequiredValidation is returned when the RequestType is required but not provided.
	ErrcreateMessageApplicationXMLRequestRequestTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestType is required", Path: "createMessageApplicationXMLRequest.RequestType", Type: "required"}

	// ErrcreateMessageApplicationXMLRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrcreateMessageApplicationXMLRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "createMessageApplicationXMLRequest.Status", Type: "required"}
)

func ValidatecreateMessageApplicationXMLRequest(t *createMessageApplicationXMLRequest) error {
	if t == nil {
		return ErrNilcreateMessageApplicationXMLRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationName == "" {
		err := ErrcreateMessageApplicationXMLRequestApplicationNameRequiredValidation
		err.Value = t.ApplicationName
		errs = append(errs, err)
	}

	if !(regexp.MustCompile("^[1-4](,[1-4])*$").MatchString(t.RequestType)) {
		err := ErrcreateMessageApplicationXMLRequestRequestTypeCELValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.RequestType == "" {
		err := ErrcreateMessageApplicationXMLRequestRequestTypeRequiredValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrcreateMessageApplicationXMLRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*createMessageApplicationXMLRequest)(nil)

func (t *createMessageApplicationXMLRequest) Validate() error {
	return ValidatecreateMessageApplicationXMLRequest(t)
}
