// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"regexp"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilcreateMessageApplicationRequestFormTest is returned when the createMessageApplicationRequestFormTest is nil.
	ErrNilcreateMessageApplicationRequestFormTest = errors.New("input createMessageApplicationRequestFormTest is nil")

	// ErrcreateMessageApplicationRequestFormTestApplicationNameRequiredValidation is returned when the ApplicationName is required but not provided.
	ErrcreateMessageApplicationRequestFormTestApplicationNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationName is required", Path: "createMessageApplicationRequestFormTest.ApplicationName", Type: "required"}

	// ErrcreateMessageApplicationRequestFormTestRequestTypeCELValidation is the error returned when the CEL expression evaluation fails.
	ErrcreateMessageApplicationRequestFormTestRequestTypeCELValidation = govaliderrors.ValidationError{Reason: "field RequestType failed CEL validation: value.matches('^[1-4](,[1-4])*$')", Path: "createMessageApplicationRequestFormTest.RequestType", Type: "cel"}

	// ErrcreateMessageApplicationRequestFormTestRequestTypeRequiredValidation is returned when the RequestType is required but not provided.
	ErrcreateMessageApplicationRequestFormTestRequestTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestType is required", Path: "createMessageApplicationRequestFormTest.RequestType", Type: "required"}

	// ErrcreateMessageApplicationRequestFormTestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrcreateMessageApplicationRequestFormTestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "createMessageApplicationRequestFormTest.Status", Type: "required"}
)

func ValidatecreateMessageApplicationRequestFormTest(t *createMessageApplicationRequestFormTest) error {
	if t == nil {
		return ErrNilcreateMessageApplicationRequestFormTest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationName == "" {
		err := ErrcreateMessageApplicationRequestFormTestApplicationNameRequiredValidation
		err.Value = t.ApplicationName
		errs = append(errs, err)
	}

	if !(regexp.MustCompile("^[1-4](,[1-4])*$").MatchString(t.RequestType)) {
		err := ErrcreateMessageApplicationRequestFormTestRequestTypeCELValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.RequestType == "" {
		err := ErrcreateMessageApplicationRequestFormTestRequestTypeRequiredValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrcreateMessageApplicationRequestFormTestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*createMessageApplicationRequestFormTest)(nil)

func (t *createMessageApplicationRequestFormTest) Validate() error {
	return ValidatecreateMessageApplicationRequestFormTest(t)
}
