// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"regexp"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilcreateMessageApplicationRequestForm is returned when the createMessageApplicationRequestForm is nil.
	ErrNilcreateMessageApplicationRequestForm = errors.New("input createMessageApplicationRequestForm is nil")

	// ErrcreateMessageApplicationRequestFormApplicationNameRequiredValidation is returned when the ApplicationName is required but not provided.
	ErrcreateMessageApplicationRequestFormApplicationNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationName is required", Path: "createMessageApplicationRequestForm.ApplicationName", Type: "required"}

	// ErrcreateMessageApplicationRequestFormRequestTypeCELValidation is the error returned when the CEL expression evaluation fails.
	ErrcreateMessageApplicationRequestFormRequestTypeCELValidation = govaliderrors.ValidationError{Reason: "field RequestType failed CEL validation: value.matches('^[1-4](,[1-4])*$')", Path: "createMessageApplicationRequestForm.RequestType", Type: "cel"}

	// ErrcreateMessageApplicationRequestFormRequestTypeRequiredValidation is returned when the RequestType is required but not provided.
	ErrcreateMessageApplicationRequestFormRequestTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestType is required", Path: "createMessageApplicationRequestForm.RequestType", Type: "required"}

	// ErrcreateMessageApplicationRequestFormStatusRequiredValidation is returned when the Status is required but not provided.
	ErrcreateMessageApplicationRequestFormStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "createMessageApplicationRequestForm.Status", Type: "required"}
)

func ValidatecreateMessageApplicationRequestForm(t *createMessageApplicationRequestForm) error {
	if t == nil {
		return ErrNilcreateMessageApplicationRequestForm
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationName == "" {
		err := ErrcreateMessageApplicationRequestFormApplicationNameRequiredValidation
		err.Value = t.ApplicationName
		errs = append(errs, err)
	}

	if !(regexp.MustCompile("^[1-4](,[1-4])*$").MatchString(t.RequestType)) {
		err := ErrcreateMessageApplicationRequestFormRequestTypeCELValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.RequestType == "" {
		err := ErrcreateMessageApplicationRequestFormRequestTypeRequiredValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrcreateMessageApplicationRequestFormStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*createMessageApplicationRequestForm)(nil)

func (t *createMessageApplicationRequestForm) Validate() error {
	return ValidatecreateMessageApplicationRequestForm(t)
}
