// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"regexp"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilupdateMessageApplicationRequest is returned when the updateMessageApplicationRequest is nil.
	ErrNilupdateMessageApplicationRequest = errors.New("input updateMessageApplicationRequest is nil")

	// ErrupdateMessageApplicationRequestApplicationIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrupdateMessageApplicationRequestApplicationIDGTValidation = govaliderrors.ValidationError{Reason: "field ApplicationID must be greater than 0", Path: "updateMessageApplicationRequest.ApplicationID", Type: "gt"}

	// ErrupdateMessageApplicationRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrupdateMessageApplicationRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "updateMessageApplicationRequest.ApplicationID", Type: "required"}

	// ErrupdateMessageApplicationRequestApplicationNameRequiredValidation is returned when the ApplicationName is required but not provided.
	ErrupdateMessageApplicationRequestApplicationNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationName is required", Path: "updateMessageApplicationRequest.ApplicationName", Type: "required"}

	// ErrupdateMessageApplicationRequestRequestTypeCELValidation is the error returned when the CEL expression evaluation fails.
	ErrupdateMessageApplicationRequestRequestTypeCELValidation = govaliderrors.ValidationError{Reason: "field RequestType failed CEL validation: value.matches('^[1-4](,[1-4])*$')", Path: "updateMessageApplicationRequest.RequestType", Type: "cel"}

	// ErrupdateMessageApplicationRequestRequestTypeRequiredValidation is returned when the RequestType is required but not provided.
	ErrupdateMessageApplicationRequestRequestTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestType is required", Path: "updateMessageApplicationRequest.RequestType", Type: "required"}

	// ErrupdateMessageApplicationRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrupdateMessageApplicationRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "updateMessageApplicationRequest.Status", Type: "required"}
)

func ValidateupdateMessageApplicationRequest(t *updateMessageApplicationRequest) error {
	if t == nil {
		return ErrNilupdateMessageApplicationRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ApplicationID > 0) {
		err := ErrupdateMessageApplicationRequestApplicationIDGTValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.ApplicationID == 0 {
		err := ErrupdateMessageApplicationRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.ApplicationName == "" {
		err := ErrupdateMessageApplicationRequestApplicationNameRequiredValidation
		err.Value = t.ApplicationName
		errs = append(errs, err)
	}

	if !(regexp.MustCompile("^[1-4](,[1-4])*$").MatchString(t.RequestType)) {
		err := ErrupdateMessageApplicationRequestRequestTypeCELValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.RequestType == "" {
		err := ErrupdateMessageApplicationRequestRequestTypeRequiredValidation
		err.Value = t.RequestType
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrupdateMessageApplicationRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*updateMessageApplicationRequest)(nil)

func (t *updateMessageApplicationRequest) Validate() error {
	return ValidateupdateMessageApplicationRequest(t)
}
