// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilSendBulkSMSRequestOld is returned when the SendBulkSMSRequestOld is nil.
	ErrNilSendBulkSMSRequestOld = errors.New("input SendBulkSMSRequestOld is nil")

	// ErrSendBulkSMSRequestOldUniqueIDRequiredValidation is returned when the UniqueID is required but not provided.
	ErrSendBulkSMSRequestOldUniqueIDRequiredValidation = govaliderrors.ValidationError{Reason: "field UniqueID is required", Path: "SendBulkSMSRequestOld.UniqueID", Type: "required"}

	// ErrSendBulkSMSRequestOldSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrSendBulkSMSRequestOldSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "SendBulkSMSRequestOld.SenderID", Type: "required"}

	// ErrSendBulkSMSRequestOldTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrSendBulkSMSRequestOldTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "SendBulkSMSRequestOld.TemplateID", Type: "required"}

	// ErrSendBulkSMSRequestOldMessageTypeRequiredValidation is returned when the MessageType is required but not provided.
	ErrSendBulkSMSRequestOldMessageTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageType is required", Path: "SendBulkSMSRequestOld.MessageType", Type: "required"}
)

func ValidateSendBulkSMSRequestOld(t *SendBulkSMSRequestOld) error {
	if t == nil {
		return ErrNilSendBulkSMSRequestOld
	}

	var errs govaliderrors.ValidationErrors

	if t.UniqueID == "" {
		err := ErrSendBulkSMSRequestOldUniqueIDRequiredValidation
		err.Value = t.UniqueID
		errs = append(errs, err)
	}

	if t.SenderID == "" {
		err := ErrSendBulkSMSRequestOldSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrSendBulkSMSRequestOldTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if t.MessageType == "" {
		err := ErrSendBulkSMSRequestOldMessageTypeRequiredValidation
		err.Value = t.MessageType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SendBulkSMSRequestOld)(nil)

func (t *SendBulkSMSRequestOld) Validate() error {
	return ValidateSendBulkSMSRequestOld(t)
}
