// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilinitiateBulkSMSRequest is returned when the initiateBulkSMSRequest is nil.
	ErrNilinitiateBulkSMSRequest = errors.New("input initiateBulkSMSRequest is nil")

	// ErrinitiateBulkSMSRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrinitiateBulkSMSRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "initiateBulkSMSRequest.ApplicationID", Type: "required"}

	// ErrinitiateBulkSMSRequestTemplateNameRequiredValidation is returned when the TemplateName is required but not provided.
	ErrinitiateBulkSMSRequestTemplateNameRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateName is required", Path: "initiateBulkSMSRequest.TemplateName", Type: "required"}

	// ErrinitiateBulkSMSRequestMobileNoRequiredValidation is returned when the MobileNo is required but not provided.
	ErrinitiateBulkSMSRequestMobileNoRequiredValidation = govaliderrors.ValidationError{Reason: "field MobileNo is required", Path: "initiateBulkSMSRequest.MobileNo", Type: "required"}

	// ErrinitiateBulkSMSRequestTestMessageRequiredValidation is returned when the TestMessage is required but not provided.
	ErrinitiateBulkSMSRequestTestMessageRequiredValidation = govaliderrors.ValidationError{Reason: "field TestMessage is required", Path: "initiateBulkSMSRequest.TestMessage", Type: "required"}
)

func ValidateinitiateBulkSMSRequest(t *initiateBulkSMSRequest) error {
	if t == nil {
		return ErrNilinitiateBulkSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrinitiateBulkSMSRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.TemplateName == "" {
		err := ErrinitiateBulkSMSRequestTemplateNameRequiredValidation
		err.Value = t.TemplateName
		errs = append(errs, err)
	}

	if t.MobileNo == "" {
		err := ErrinitiateBulkSMSRequestMobileNoRequiredValidation
		err.Value = t.MobileNo
		errs = append(errs, err)
	}

	if t.TestMessage == "" {
		err := ErrinitiateBulkSMSRequestTestMessageRequiredValidation
		err.Value = t.TestMessage
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*initiateBulkSMSRequest)(nil)

func (t *initiateBulkSMSRequest) Validate() error {
	return ValidateinitiateBulkSMSRequest(t)
}
