// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilvalidateTestSMSRequest is returned when the validateTestSMSRequest is nil.
	ErrNilvalidateTestSMSRequest = errors.New("input validateTestSMSRequest is nil")

	// ErrvalidateTestSMSRequestReferenceIDRequiredValidation is returned when the ReferenceID is required but not provided.
	ErrvalidateTestSMSRequestReferenceIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ReferenceID is required", Path: "validateTestSMSRequest.ReferenceID", Type: "required"}

	// ErrvalidateTestSMSRequestTestStringRequiredValidation is returned when the TestString is required but not provided.
	ErrvalidateTestSMSRequestTestStringRequiredValidation = govaliderrors.ValidationError{Reason: "field TestString is required", Path: "validateTestSMSRequest.TestString", Type: "required"}
)

func ValidatevalidateTestSMSRequest(t *validateTestSMSRequest) error {
	if t == nil {
		return ErrNilvalidateTestSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ReferenceID == "" {
		err := ErrvalidateTestSMSRequestReferenceIDRequiredValidation
		err.Value = t.ReferenceID
		errs = append(errs, err)
	}

	if t.TestString == "" {
		err := ErrvalidateTestSMSRequestTestStringRequiredValidation
		err.Value = t.TestString
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*validateTestSMSRequest)(nil)

func (t *validateTestSMSRequest) Validate() error {
	return ValidatevalidateTestSMSRequest(t)
}
