// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilsendBulkSMSRequest is returned when the sendBulkSMSRequest is nil.
	ErrNilsendBulkSMSRequest = errors.New("input sendBulkSMSRequest is nil")

	// ErrsendBulkSMSRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrsendBulkSMSRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "sendBulkSMSRequest.SenderID", Type: "required"}

	// ErrsendBulkSMSRequestMobileNumberRequiredValidation is returned when the MobileNumber is required but not provided.
	ErrsendBulkSMSRequestMobileNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field MobileNumber is required", Path: "sendBulkSMSRequest.MobileNumber", Type: "required"}

	// ErrsendBulkSMSRequestMessageTypeRequiredValidation is returned when the MessageType is required but not provided.
	ErrsendBulkSMSRequestMessageTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageType is required", Path: "sendBulkSMSRequest.MessageType", Type: "required"}

	// ErrsendBulkSMSRequestMessageTextRequiredValidation is returned when the MessageText is required but not provided.
	ErrsendBulkSMSRequestMessageTextRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageText is required", Path: "sendBulkSMSRequest.MessageText", Type: "required"}

	// ErrsendBulkSMSRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrsendBulkSMSRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "sendBulkSMSRequest.TemplateID", Type: "required"}

	// ErrsendBulkSMSRequestEntityIDRequiredValidation is returned when the EntityID is required but not provided.
	ErrsendBulkSMSRequestEntityIDRequiredValidation = govaliderrors.ValidationError{Reason: "field EntityID is required", Path: "sendBulkSMSRequest.EntityID", Type: "required"}
)

func ValidatesendBulkSMSRequest(t *sendBulkSMSRequest) error {
	if t == nil {
		return ErrNilsendBulkSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SenderID == "" {
		err := ErrsendBulkSMSRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.MobileNumber == "" {
		err := ErrsendBulkSMSRequestMobileNumberRequiredValidation
		err.Value = t.MobileNumber
		errs = append(errs, err)
	}

	if t.MessageType == "" {
		err := ErrsendBulkSMSRequestMessageTypeRequiredValidation
		err.Value = t.MessageType
		errs = append(errs, err)
	}

	if t.MessageText == "" {
		err := ErrsendBulkSMSRequestMessageTextRequiredValidation
		err.Value = t.MessageText
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrsendBulkSMSRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if t.EntityID == "" {
		err := ErrsendBulkSMSRequestEntityIDRequiredValidation
		err.Value = t.EntityID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*sendBulkSMSRequest)(nil)

func (t *sendBulkSMSRequest) Validate() error {
	return ValidatesendBulkSMSRequest(t)
}
