// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilcreateSMSRequest is returned when the createSMSRequest is nil.
	ErrNilcreateSMSRequest = errors.New("input createSMSRequest is nil")

	// ErrcreateSMSRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrcreateSMSRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "createSMSRequest.ApplicationID", Type: "required"}

	// ErrcreateSMSRequestFacilityIDRequiredValidation is returned when the FacilityID is required but not provided.
	ErrcreateSMSRequestFacilityIDRequiredValidation = govaliderrors.ValidationError{Reason: "field FacilityID is required", Path: "createSMSRequest.FacilityID", Type: "required"}

	// ErrcreateSMSRequestPriorityRequiredValidation is returned when the Priority is required but not provided.
	ErrcreateSMSRequestPriorityRequiredValidation = govaliderrors.ValidationError{Reason: "field Priority is required", Path: "createSMSRequest.Priority", Type: "required"}

	// ErrcreateSMSRequestMessageTextRequiredValidation is returned when the MessageText is required but not provided.
	ErrcreateSMSRequestMessageTextRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageText is required", Path: "createSMSRequest.MessageText", Type: "required"}

	// ErrcreateSMSRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrcreateSMSRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "createSMSRequest.SenderID", Type: "required"}

	// ErrcreateSMSRequestMobileNumbersRequiredValidation is returned when the MobileNumbers is required but not provided.
	ErrcreateSMSRequestMobileNumbersRequiredValidation = govaliderrors.ValidationError{Reason: "field MobileNumbers is required", Path: "createSMSRequest.MobileNumbers", Type: "required"}

	// ErrcreateSMSRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrcreateSMSRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "createSMSRequest.TemplateID", Type: "required"}
)

func ValidatecreateSMSRequest(t *createSMSRequest) error {
	if t == nil {
		return ErrNilcreateSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrcreateSMSRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.FacilityID == "" {
		err := ErrcreateSMSRequestFacilityIDRequiredValidation
		err.Value = t.FacilityID
		errs = append(errs, err)
	}

	if t.Priority == 0 {
		err := ErrcreateSMSRequestPriorityRequiredValidation
		err.Value = t.Priority
		errs = append(errs, err)
	}

	if t.MessageText == "" {
		err := ErrcreateSMSRequestMessageTextRequiredValidation
		err.Value = t.MessageText
		errs = append(errs, err)
	}

	if t.SenderID == "" {
		err := ErrcreateSMSRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.MobileNumbers == "" {
		err := ErrcreateSMSRequestMobileNumbersRequiredValidation
		err.Value = t.MobileNumbers
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrcreateSMSRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*createSMSRequest)(nil)

func (t *createSMSRequest) Validate() error {
	return ValidatecreateSMSRequest(t)
}
