// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilfetchMessageProviderRequest is returned when the fetchMessageProviderRequest is nil.
	ErrNilfetchMessageProviderRequest = errors.New("input fetchMessageProviderRequest is nil")

	// ErrfetchMessageProviderRequestProviderIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrfetchMessageProviderRequestProviderIDGTValidation = govaliderrors.ValidationError{Reason: "field ProviderID must be greater than 0", Path: "fetchMessageProviderRequest.ProviderID", Type: "gt"}

	// ErrfetchMessageProviderRequestProviderIDRequiredValidation is returned when the ProviderID is required but not provided.
	ErrfetchMessageProviderRequestProviderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderID is required", Path: "fetchMessageProviderRequest.ProviderID", Type: "required"}
)

func ValidatefetchMessageProviderRequest(t *fetchMessageProviderRequest) error {
	if t == nil {
		return ErrNilfetchMessageProviderRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ProviderID > 0) {
		err := ErrfetchMessageProviderRequestProviderIDGTValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if t.ProviderID == 0 {
		err := ErrfetchMessageProviderRequestProviderIDRequiredValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*fetchMessageProviderRequest)(nil)

func (t *fetchMessageProviderRequest) Validate() error {
	return ValidatefetchMessageProviderRequest(t)
}
