// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilcreateMessageProviderRequest is returned when the createMessageProviderRequest is nil.
	ErrNilcreateMessageProviderRequest = errors.New("input createMessageProviderRequest is nil")

	// ErrcreateMessageProviderRequestProviderNameRequiredValidation is returned when the ProviderName is required but not provided.
	ErrcreateMessageProviderRequestProviderNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderName is required", Path: "createMessageProviderRequest.ProviderName", Type: "required"}

	// ErrcreateMessageProviderRequestShortNameRequiredValidation is returned when the ShortName is required but not provided.
	ErrcreateMessageProviderRequestShortNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ShortName is required", Path: "createMessageProviderRequest.ShortName", Type: "required"}

	// ErrcreateMessageProviderRequestServicesRequiredValidation is returned when the Services is required but not provided.
	ErrcreateMessageProviderRequestServicesRequiredValidation = govaliderrors.ValidationError{Reason: "field Services is required", Path: "createMessageProviderRequest.Services", Type: "required"}

	// ErrcreateMessageProviderRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrcreateMessageProviderRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "createMessageProviderRequest.Status", Type: "required"}
)

func ValidatecreateMessageProviderRequest(t *createMessageProviderRequest) error {
	if t == nil {
		return ErrNilcreateMessageProviderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProviderName == "" {
		err := ErrcreateMessageProviderRequestProviderNameRequiredValidation
		err.Value = t.ProviderName
		errs = append(errs, err)
	}

	if t.ShortName == "" {
		err := ErrcreateMessageProviderRequestShortNameRequiredValidation
		err.Value = t.ShortName
		errs = append(errs, err)
	}

	if t.Services == "" {
		err := ErrcreateMessageProviderRequestServicesRequiredValidation
		err.Value = t.Services
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrcreateMessageProviderRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*createMessageProviderRequest)(nil)

func (t *createMessageProviderRequest) Validate() error {
	return ValidatecreateMessageProviderRequest(t)
}
