// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNiltoggleMessageProviderStatusRequest is returned when the toggleMessageProviderStatusRequest is nil.
	ErrNiltoggleMessageProviderStatusRequest = errors.New("input toggleMessageProviderStatusRequest is nil")

	// ErrtoggleMessageProviderStatusRequestProviderIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrtoggleMessageProviderStatusRequestProviderIDGTValidation = govaliderrors.ValidationError{Reason: "field ProviderID must be greater than 0", Path: "toggleMessageProviderStatusRequest.ProviderID", Type: "gt"}

	// ErrtoggleMessageProviderStatusRequestProviderIDRequiredValidation is returned when the ProviderID is required but not provided.
	ErrtoggleMessageProviderStatusRequestProviderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderID is required", Path: "toggleMessageProviderStatusRequest.ProviderID", Type: "required"}
)

func ValidatetoggleMessageProviderStatusRequest(t *toggleMessageProviderStatusRequest) error {
	if t == nil {
		return ErrNiltoggleMessageProviderStatusRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ProviderID > 0) {
		err := ErrtoggleMessageProviderStatusRequestProviderIDGTValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if t.ProviderID == 0 {
		err := ErrtoggleMessageProviderStatusRequestProviderIDRequiredValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*toggleMessageProviderStatusRequest)(nil)

func (t *toggleMessageProviderStatusRequest) Validate() error {
	return ValidatetoggleMessageProviderStatusRequest(t)
}
