// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"
	"regexp"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilupdateMessageProviderRequest is returned when the updateMessageProviderRequest is nil.
	ErrNilupdateMessageProviderRequest = errors.New("input updateMessageProviderRequest is nil")

	// ErrupdateMessageProviderRequestProviderIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrupdateMessageProviderRequestProviderIDGTValidation = govaliderrors.ValidationError{Reason: "field ProviderID must be greater than 0", Path: "updateMessageProviderRequest.ProviderID", Type: "gt"}

	// ErrupdateMessageProviderRequestProviderIDRequiredValidation is returned when the ProviderID is required but not provided.
	ErrupdateMessageProviderRequestProviderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderID is required", Path: "updateMessageProviderRequest.ProviderID", Type: "required"}

	// ErrupdateMessageProviderRequestProviderNameRequiredValidation is returned when the ProviderName is required but not provided.
	ErrupdateMessageProviderRequestProviderNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderName is required", Path: "updateMessageProviderRequest.ProviderName", Type: "required"}

	// ErrupdateMessageProviderRequestServicesCELValidation is the error returned when the CEL expression evaluation fails.
	ErrupdateMessageProviderRequestServicesCELValidation = govaliderrors.ValidationError{Reason: "field Services failed CEL validation: value.matches('^[1-4](,[1-4])*$')", Path: "updateMessageProviderRequest.Services", Type: "cel"}

	// ErrupdateMessageProviderRequestServicesRequiredValidation is returned when the Services is required but not provided.
	ErrupdateMessageProviderRequestServicesRequiredValidation = govaliderrors.ValidationError{Reason: "field Services is required", Path: "updateMessageProviderRequest.Services", Type: "required"}

	// ErrupdateMessageProviderRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrupdateMessageProviderRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "updateMessageProviderRequest.Status", Type: "required"}
)

func ValidateupdateMessageProviderRequest(t *updateMessageProviderRequest) error {
	if t == nil {
		return ErrNilupdateMessageProviderRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.ProviderID > 0) {
		err := ErrupdateMessageProviderRequestProviderIDGTValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if t.ProviderID == 0 {
		err := ErrupdateMessageProviderRequestProviderIDRequiredValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if t.ProviderName == "" {
		err := ErrupdateMessageProviderRequestProviderNameRequiredValidation
		err.Value = t.ProviderName
		errs = append(errs, err)
	}

	if !(regexp.MustCompile("^[1-4](,[1-4])*$").MatchString(t.Services)) {
		err := ErrupdateMessageProviderRequestServicesCELValidation
		err.Value = t.Services
		errs = append(errs, err)
	}

	if t.Services == "" {
		err := ErrupdateMessageProviderRequestServicesRequiredValidation
		err.Value = t.Services
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrupdateMessageProviderRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*updateMessageProviderRequest)(nil)

func (t *updateMessageProviderRequest) Validate() error {
	return ValidateupdateMessageProviderRequest(t)
}
