// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilsentSMSStatusReportRequest is returned when the sentSMSStatusReportRequest is nil.
	ErrNilsentSMSStatusReportRequest = errors.New("input sentSMSStatusReportRequest is nil")

	// ErrsentSMSStatusReportRequestFromDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrsentSMSStatusReportRequestFromDateDateValidation = govaliderrors.ValidationError{Reason: "field FromDate must be a valid date (dd/mm/yy)", Path: "sentSMSStatusReportRequest.FromDate", Type: "date"}

	// ErrsentSMSStatusReportRequestFromDateRequiredValidation is returned when the FromDate is required but not provided.
	ErrsentSMSStatusReportRequestFromDateRequiredValidation = govaliderrors.ValidationError{Reason: "field FromDate is required", Path: "sentSMSStatusReportRequest.FromDate", Type: "required"}

	// ErrsentSMSStatusReportRequestToDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErrsentSMSStatusReportRequestToDateDateValidation = govaliderrors.ValidationError{Reason: "field ToDate must be a valid date (dd/mm/yy)", Path: "sentSMSStatusReportRequest.ToDate", Type: "date"}

	// ErrsentSMSStatusReportRequestToDateRequiredValidation is returned when the ToDate is required but not provided.
	ErrsentSMSStatusReportRequestToDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ToDate is required", Path: "sentSMSStatusReportRequest.ToDate", Type: "required"}
)

func ValidatesentSMSStatusReportRequest(t *sentSMSStatusReportRequest) error {
	if t == nil {
		return ErrNilsentSMSStatusReportRequest
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidDateDDMMYY(t.FromDate) {
		err := ErrsentSMSStatusReportRequestFromDateDateValidation
		err.Value = t.FromDate
		errs = append(errs, err)
	}

	if t.FromDate == "" {
		err := ErrsentSMSStatusReportRequestFromDateRequiredValidation
		err.Value = t.FromDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.ToDate) {
		err := ErrsentSMSStatusReportRequestToDateDateValidation
		err.Value = t.ToDate
		errs = append(errs, err)
	}

	if t.ToDate == "" {
		err := ErrsentSMSStatusReportRequestToDateRequiredValidation
		err.Value = t.ToDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*sentSMSStatusReportRequest)(nil)

func (t *sentSMSStatusReportRequest) Validate() error {
	return ValidatesentSMSStatusReportRequest(t)
}
