// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilaggregateSMSUsageReportRequest is returned when the aggregateSMSUsageReportRequest is nil.
	ErrNilaggregateSMSUsageReportRequest = errors.New("input aggregateSMSUsageReportRequest is nil")

	// ErraggregateSMSUsageReportRequestFromDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErraggregateSMSUsageReportRequestFromDateDateValidation = govaliderrors.ValidationError{Reason: "field FromDate must be a valid date (dd/mm/yy)", Path: "aggregateSMSUsageReportRequest.FromDate", Type: "date"}

	// ErraggregateSMSUsageReportRequestFromDateRequiredValidation is returned when the FromDate is required but not provided.
	ErraggregateSMSUsageReportRequestFromDateRequiredValidation = govaliderrors.ValidationError{Reason: "field FromDate is required", Path: "aggregateSMSUsageReportRequest.FromDate", Type: "required"}

	// ErraggregateSMSUsageReportRequestToDateDateValidation is the error returned when the field is not a valid date (dd/mm/yy).
	ErraggregateSMSUsageReportRequestToDateDateValidation = govaliderrors.ValidationError{Reason: "field ToDate must be a valid date (dd/mm/yy)", Path: "aggregateSMSUsageReportRequest.ToDate", Type: "date"}

	// ErraggregateSMSUsageReportRequestToDateRequiredValidation is returned when the ToDate is required but not provided.
	ErraggregateSMSUsageReportRequestToDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ToDate is required", Path: "aggregateSMSUsageReportRequest.ToDate", Type: "required"}

	// ErraggregateSMSUsageReportRequestReportTypeRequiredValidation is returned when the ReportType is required but not provided.
	ErraggregateSMSUsageReportRequestReportTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field ReportType is required", Path: "aggregateSMSUsageReportRequest.ReportType", Type: "required"}
)

func ValidateaggregateSMSUsageReportRequest(t *aggregateSMSUsageReportRequest) error {
	if t == nil {
		return ErrNilaggregateSMSUsageReportRequest
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidDateDDMMYY(t.FromDate) {
		err := ErraggregateSMSUsageReportRequestFromDateDateValidation
		err.Value = t.FromDate
		errs = append(errs, err)
	}

	if t.FromDate == "" {
		err := ErraggregateSMSUsageReportRequestFromDateRequiredValidation
		err.Value = t.FromDate
		errs = append(errs, err)
	}

	if !validationhelper.IsValidDateDDMMYY(t.ToDate) {
		err := ErraggregateSMSUsageReportRequestToDateDateValidation
		err.Value = t.ToDate
		errs = append(errs, err)
	}

	if t.ToDate == "" {
		err := ErraggregateSMSUsageReportRequestToDateRequiredValidation
		err.Value = t.ToDate
		errs = append(errs, err)
	}

	if t.ReportType == 0 {
		err := ErraggregateSMSUsageReportRequestReportTypeRequiredValidation
		err.Value = t.ReportType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*aggregateSMSUsageReportRequest)(nil)

func (t *aggregateSMSUsageReportRequest) Validate() error {
	return ValidateaggregateSMSUsageReportRequest(t)
}
