// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilupdateTemplateRequest is returned when the updateTemplateRequest is nil.
	ErrNilupdateTemplateRequest = errors.New("input updateTemplateRequest is nil")

	// ErrupdateTemplateRequestTemplateLocalIDRequiredValidation is returned when the TemplateLocalID is required but not provided.
	ErrupdateTemplateRequestTemplateLocalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateLocalID is required", Path: "updateTemplateRequest.TemplateLocalID", Type: "required"}

	// ErrupdateTemplateRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrupdateTemplateRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "updateTemplateRequest.ApplicationID", Type: "required"}

	// ErrupdateTemplateRequestTemplateNameRequiredValidation is returned when the TemplateName is required but not provided.
	ErrupdateTemplateRequestTemplateNameRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateName is required", Path: "updateTemplateRequest.TemplateName", Type: "required"}

	// ErrupdateTemplateRequestTemplateFormatRequiredValidation is returned when the TemplateFormat is required but not provided.
	ErrupdateTemplateRequestTemplateFormatRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateFormat is required", Path: "updateTemplateRequest.TemplateFormat", Type: "required"}

	// ErrupdateTemplateRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrupdateTemplateRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "updateTemplateRequest.SenderID", Type: "required"}

	// ErrupdateTemplateRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrupdateTemplateRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "updateTemplateRequest.TemplateID", Type: "required"}

	// ErrupdateTemplateRequestGatewayRequiredValidation is returned when the Gateway is required but not provided.
	ErrupdateTemplateRequestGatewayRequiredValidation = govaliderrors.ValidationError{Reason: "field Gateway is required", Path: "updateTemplateRequest.Gateway", Type: "required"}

	// ErrupdateTemplateRequestMessageTypeRequiredValidation is returned when the MessageType is required but not provided.
	ErrupdateTemplateRequestMessageTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageType is required", Path: "updateTemplateRequest.MessageType", Type: "required"}

	// ErrupdateTemplateRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrupdateTemplateRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "updateTemplateRequest.Status", Type: "required"}
)

func ValidateupdateTemplateRequest(t *updateTemplateRequest) error {
	if t == nil {
		return ErrNilupdateTemplateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TemplateLocalID == 0 {
		err := ErrupdateTemplateRequestTemplateLocalIDRequiredValidation
		err.Value = t.TemplateLocalID
		errs = append(errs, err)
	}

	if t.ApplicationID == "" {
		err := ErrupdateTemplateRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.TemplateName == "" {
		err := ErrupdateTemplateRequestTemplateNameRequiredValidation
		err.Value = t.TemplateName
		errs = append(errs, err)
	}

	if t.TemplateFormat == "" {
		err := ErrupdateTemplateRequestTemplateFormatRequiredValidation
		err.Value = t.TemplateFormat
		errs = append(errs, err)
	}

	if t.SenderID == "" {
		err := ErrupdateTemplateRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrupdateTemplateRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if t.Gateway == "" {
		err := ErrupdateTemplateRequestGatewayRequiredValidation
		err.Value = t.Gateway
		errs = append(errs, err)
	}

	if t.MessageType == "" {
		err := ErrupdateTemplateRequestMessageTypeRequiredValidation
		err.Value = t.MessageType
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrupdateTemplateRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*updateTemplateRequest)(nil)

func (t *updateTemplateRequest) Validate() error {
	return ValidateupdateTemplateRequest(t)
}
