// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilfetchTemplateByApplicationRequest is returned when the fetchTemplateByApplicationRequest is nil.
	ErrNilfetchTemplateByApplicationRequest = errors.New("input fetchTemplateByApplicationRequest is nil")

	// ErrfetchTemplateByApplicationRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrfetchTemplateByApplicationRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "fetchTemplateByApplicationRequest.ApplicationID", Type: "required"}
)

func ValidatefetchTemplateByApplicationRequest(t *fetchTemplateByApplicationRequest) error {
	if t == nil {
		return ErrNilfetchTemplateByApplicationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrfetchTemplateByApplicationRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*fetchTemplateByApplicationRequest)(nil)

func (t *fetchTemplateByApplicationRequest) Validate() error {
	return ValidatefetchTemplateByApplicationRequest(t)
}
