// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilfetchTemplateRequest is returned when the fetchTemplateRequest is nil.
	ErrNilfetchTemplateRequest = errors.New("input fetchTemplateRequest is nil")

	// ErrfetchTemplateRequestTemplateLocalIDRequiredValidation is returned when the TemplateLocalID is required but not provided.
	ErrfetchTemplateRequestTemplateLocalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateLocalID is required", Path: "fetchTemplateRequest.TemplateLocalID", Type: "required"}
)

func ValidatefetchTemplateRequest(t *fetchTemplateRequest) error {
	if t == nil {
		return ErrNilfetchTemplateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TemplateLocalID == 0 {
		err := ErrfetchTemplateRequestTemplateLocalIDRequiredValidation
		err.Value = t.TemplateLocalID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*fetchTemplateRequest)(nil)

func (t *fetchTemplateRequest) Validate() error {
	return ValidatefetchTemplateRequest(t)
}
