// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNiltoggleTemplateStatusRequest is returned when the toggleTemplateStatusRequest is nil.
	ErrNiltoggleTemplateStatusRequest = errors.New("input toggleTemplateStatusRequest is nil")

	// ErrtoggleTemplateStatusRequestTemplateLocalIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrtoggleTemplateStatusRequestTemplateLocalIDGTValidation = govaliderrors.ValidationError{Reason: "field TemplateLocalID must be greater than 0", Path: "toggleTemplateStatusRequest.TemplateLocalID", Type: "gt"}

	// ErrtoggleTemplateStatusRequestTemplateLocalIDRequiredValidation is returned when the TemplateLocalID is required but not provided.
	ErrtoggleTemplateStatusRequestTemplateLocalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateLocalID is required", Path: "toggleTemplateStatusRequest.TemplateLocalID", Type: "required"}
)

func ValidatetoggleTemplateStatusRequest(t *toggleTemplateStatusRequest) error {
	if t == nil {
		return ErrNiltoggleTemplateStatusRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.TemplateLocalID > 0) {
		err := ErrtoggleTemplateStatusRequestTemplateLocalIDGTValidation
		err.Value = t.TemplateLocalID
		errs = append(errs, err)
	}

	if t.TemplateLocalID == 0 {
		err := ErrtoggleTemplateStatusRequestTemplateLocalIDRequiredValidation
		err.Value = t.TemplateLocalID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*toggleTemplateStatusRequest)(nil)

func (t *toggleTemplateStatusRequest) Validate() error {
	return ValidatetoggleTemplateStatusRequest(t)
}
