// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilcreateTemplateRequest is returned when the createTemplateRequest is nil.
	ErrNilcreateTemplateRequest = errors.New("input createTemplateRequest is nil")

	// ErrcreateTemplateRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrcreateTemplateRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "createTemplateRequest.ApplicationID", Type: "required"}

	// ErrcreateTemplateRequestTemplateNameRequiredValidation is returned when the TemplateName is required but not provided.
	ErrcreateTemplateRequestTemplateNameRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateName is required", Path: "createTemplateRequest.TemplateName", Type: "required"}

	// ErrcreateTemplateRequestTemplateFormatRequiredValidation is returned when the TemplateFormat is required but not provided.
	ErrcreateTemplateRequestTemplateFormatRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateFormat is required", Path: "createTemplateRequest.TemplateFormat", Type: "required"}

	// ErrcreateTemplateRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrcreateTemplateRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "createTemplateRequest.SenderID", Type: "required"}

	// ErrcreateTemplateRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrcreateTemplateRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "createTemplateRequest.TemplateID", Type: "required"}

	// ErrcreateTemplateRequestGatewayRequiredValidation is returned when the Gateway is required but not provided.
	ErrcreateTemplateRequestGatewayRequiredValidation = govaliderrors.ValidationError{Reason: "field Gateway is required", Path: "createTemplateRequest.Gateway", Type: "required"}

	// ErrcreateTemplateRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrcreateTemplateRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "createTemplateRequest.Status", Type: "required"}

	// ErrcreateTemplateRequestMessageTypeRequiredValidation is returned when the MessageType is required but not provided.
	ErrcreateTemplateRequestMessageTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageType is required", Path: "createTemplateRequest.MessageType", Type: "required"}
)

func ValidatecreateTemplateRequest(t *createTemplateRequest) error {
	if t == nil {
		return ErrNilcreateTemplateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrcreateTemplateRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.TemplateName == "" {
		err := ErrcreateTemplateRequestTemplateNameRequiredValidation
		err.Value = t.TemplateName
		errs = append(errs, err)
	}

	if t.TemplateFormat == "" {
		err := ErrcreateTemplateRequestTemplateFormatRequiredValidation
		err.Value = t.TemplateFormat
		errs = append(errs, err)
	}

	if t.SenderID == "" {
		err := ErrcreateTemplateRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrcreateTemplateRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if t.Gateway == "" {
		err := ErrcreateTemplateRequestGatewayRequiredValidation
		err.Value = t.Gateway
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrcreateTemplateRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if t.MessageType == "" {
		err := ErrcreateTemplateRequestMessageTypeRequiredValidation
		err.Value = t.MessageType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*createTemplateRequest)(nil)

func (t *createTemplateRequest) Validate() error {
	return ValidatecreateTemplateRequest(t)
}
