// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilCreateSMSRequest is returned when the CreateSMSRequest is nil.
	ErrNilCreateSMSRequest = errors.New("input CreateSMSRequest is nil")

	// ErrCreateSMSRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrCreateSMSRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "CreateSMSRequest.ApplicationID", Type: "required"}

	// ErrCreateSMSRequestFacilityIDRequiredValidation is returned when the FacilityID is required but not provided.
	ErrCreateSMSRequestFacilityIDRequiredValidation = govaliderrors.ValidationError{Reason: "field FacilityID is required", Path: "CreateSMSRequest.FacilityID", Type: "required"}

	// ErrCreateSMSRequestPriorityRequiredValidation is returned when the Priority is required but not provided.
	ErrCreateSMSRequestPriorityRequiredValidation = govaliderrors.ValidationError{Reason: "field Priority is required", Path: "CreateSMSRequest.Priority", Type: "required"}

	// ErrCreateSMSRequestMessageTextRequiredValidation is returned when the MessageText is required but not provided.
	ErrCreateSMSRequestMessageTextRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageText is required", Path: "CreateSMSRequest.MessageText", Type: "required"}

	// ErrCreateSMSRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrCreateSMSRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "CreateSMSRequest.SenderID", Type: "required"}

	// ErrCreateSMSRequestMobileNumbersRequiredValidation is returned when the MobileNumbers is required but not provided.
	ErrCreateSMSRequestMobileNumbersRequiredValidation = govaliderrors.ValidationError{Reason: "field MobileNumbers is required", Path: "CreateSMSRequest.MobileNumbers", Type: "required"}

	// ErrCreateSMSRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrCreateSMSRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "CreateSMSRequest.TemplateID", Type: "required"}
)

func ValidateCreateSMSRequest(t *CreateSMSRequest) error {
	if t == nil {
		return ErrNilCreateSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrCreateSMSRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.FacilityID == "" {
		err := ErrCreateSMSRequestFacilityIDRequiredValidation
		err.Value = t.FacilityID
		errs = append(errs, err)
	}

	if t.Priority == 0 {
		err := ErrCreateSMSRequestPriorityRequiredValidation
		err.Value = t.Priority
		errs = append(errs, err)
	}

	if t.MessageText == "" {
		err := ErrCreateSMSRequestMessageTextRequiredValidation
		err.Value = t.MessageText
		errs = append(errs, err)
	}

	if t.SenderID == "" {
		err := ErrCreateSMSRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.MobileNumbers == "" {
		err := ErrCreateSMSRequestMobileNumbersRequiredValidation
		err.Value = t.MobileNumbers
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrCreateSMSRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateSMSRequest)(nil)

func (t *CreateSMSRequest) Validate() error {
	return ValidateCreateSMSRequest(t)
}
