// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilToggleMessageProviderStatusRequest is returned when the ToggleMessageProviderStatusRequest is nil.
	ErrNilToggleMessageProviderStatusRequest = errors.New("input ToggleMessageProviderStatusRequest is nil")

	// ErrToggleMessageProviderStatusRequestProviderIDRequiredValidation is returned when the ProviderID is required but not provided.
	ErrToggleMessageProviderStatusRequestProviderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderID is required", Path: "ToggleMessageProviderStatusRequest.ProviderID", Type: "required"}
)

func ValidateToggleMessageProviderStatusRequest(t *ToggleMessageProviderStatusRequest) error {
	if t == nil {
		return ErrNilToggleMessageProviderStatusRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProviderID == 0 {
		err := ErrToggleMessageProviderStatusRequestProviderIDRequiredValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ToggleMessageProviderStatusRequest)(nil)

func (t *ToggleMessageProviderStatusRequest) Validate() error {
	return ValidateToggleMessageProviderStatusRequest(t)
}
