// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilUpdateMessageProviderRequest is returned when the UpdateMessageProviderRequest is nil.
	ErrNilUpdateMessageProviderRequest = errors.New("input UpdateMessageProviderRequest is nil")

	// ErrUpdateMessageProviderRequestProviderIDRequiredValidation is returned when the ProviderID is required but not provided.
	ErrUpdateMessageProviderRequestProviderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderID is required", Path: "UpdateMessageProviderRequest.ProviderID", Type: "required"}

	// ErrUpdateMessageProviderRequestProviderNameRequiredValidation is returned when the ProviderName is required but not provided.
	ErrUpdateMessageProviderRequestProviderNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderName is required", Path: "UpdateMessageProviderRequest.ProviderName", Type: "required"}

	// ErrUpdateMessageProviderRequestServicesRequiredValidation is returned when the Services is required but not provided.
	ErrUpdateMessageProviderRequestServicesRequiredValidation = govaliderrors.ValidationError{Reason: "field Services is required", Path: "UpdateMessageProviderRequest.Services", Type: "required"}

	// ErrUpdateMessageProviderRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrUpdateMessageProviderRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "UpdateMessageProviderRequest.Status", Type: "required"}
)

func ValidateUpdateMessageProviderRequest(t *UpdateMessageProviderRequest) error {
	if t == nil {
		return ErrNilUpdateMessageProviderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProviderID == 0 {
		err := ErrUpdateMessageProviderRequestProviderIDRequiredValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if t.ProviderName == "" {
		err := ErrUpdateMessageProviderRequestProviderNameRequiredValidation
		err.Value = t.ProviderName
		errs = append(errs, err)
	}

	if t.Services == "" {
		err := ErrUpdateMessageProviderRequestServicesRequiredValidation
		err.Value = t.Services
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrUpdateMessageProviderRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UpdateMessageProviderRequest)(nil)

func (t *UpdateMessageProviderRequest) Validate() error {
	return ValidateUpdateMessageProviderRequest(t)
}
