// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilCreateTemplateRequest is returned when the CreateTemplateRequest is nil.
	ErrNilCreateTemplateRequest = errors.New("input CreateTemplateRequest is nil")

	// ErrCreateTemplateRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrCreateTemplateRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "CreateTemplateRequest.ApplicationID", Type: "required"}

	// ErrCreateTemplateRequestTemplateNameRequiredValidation is returned when the TemplateName is required but not provided.
	ErrCreateTemplateRequestTemplateNameRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateName is required", Path: "CreateTemplateRequest.TemplateName", Type: "required"}

	// ErrCreateTemplateRequestTemplateFormatRequiredValidation is returned when the TemplateFormat is required but not provided.
	ErrCreateTemplateRequestTemplateFormatRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateFormat is required", Path: "CreateTemplateRequest.TemplateFormat", Type: "required"}

	// ErrCreateTemplateRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrCreateTemplateRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "CreateTemplateRequest.SenderID", Type: "required"}

	// ErrCreateTemplateRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrCreateTemplateRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "CreateTemplateRequest.TemplateID", Type: "required"}

	// ErrCreateTemplateRequestGatewayRequiredValidation is returned when the Gateway is required but not provided.
	ErrCreateTemplateRequestGatewayRequiredValidation = govaliderrors.ValidationError{Reason: "field Gateway is required", Path: "CreateTemplateRequest.Gateway", Type: "required"}

	// ErrCreateTemplateRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrCreateTemplateRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "CreateTemplateRequest.Status", Type: "required"}

	// ErrCreateTemplateRequestMessageTypeRequiredValidation is returned when the MessageType is required but not provided.
	ErrCreateTemplateRequestMessageTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageType is required", Path: "CreateTemplateRequest.MessageType", Type: "required"}
)

func ValidateCreateTemplateRequest(t *CreateTemplateRequest) error {
	if t == nil {
		return ErrNilCreateTemplateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrCreateTemplateRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.TemplateName == "" {
		err := ErrCreateTemplateRequestTemplateNameRequiredValidation
		err.Value = t.TemplateName
		errs = append(errs, err)
	}

	if t.TemplateFormat == "" {
		err := ErrCreateTemplateRequestTemplateFormatRequiredValidation
		err.Value = t.TemplateFormat
		errs = append(errs, err)
	}

	if t.SenderID == "" {
		err := ErrCreateTemplateRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrCreateTemplateRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if t.Gateway == "" {
		err := ErrCreateTemplateRequestGatewayRequiredValidation
		err.Value = t.Gateway
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrCreateTemplateRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if t.MessageType == "" {
		err := ErrCreateTemplateRequestMessageTypeRequiredValidation
		err.Value = t.MessageType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateTemplateRequest)(nil)

func (t *CreateTemplateRequest) Validate() error {
	return ValidateCreateTemplateRequest(t)
}
