// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilSendBulkSMSRequest is returned when the SendBulkSMSRequest is nil.
	ErrNilSendBulkSMSRequest = errors.New("input SendBulkSMSRequest is nil")

	// ErrSendBulkSMSRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrSendBulkSMSRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "SendBulkSMSRequest.SenderID", Type: "required"}

	// ErrSendBulkSMSRequestMobileNumberRequiredValidation is returned when the MobileNumber is required but not provided.
	ErrSendBulkSMSRequestMobileNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field MobileNumber is required", Path: "SendBulkSMSRequest.MobileNumber", Type: "required"}

	// ErrSendBulkSMSRequestMessageTypeRequiredValidation is returned when the MessageType is required but not provided.
	ErrSendBulkSMSRequestMessageTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageType is required", Path: "SendBulkSMSRequest.MessageType", Type: "required"}

	// ErrSendBulkSMSRequestMessageTextRequiredValidation is returned when the MessageText is required but not provided.
	ErrSendBulkSMSRequestMessageTextRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageText is required", Path: "SendBulkSMSRequest.MessageText", Type: "required"}

	// ErrSendBulkSMSRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrSendBulkSMSRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "SendBulkSMSRequest.TemplateID", Type: "required"}

	// ErrSendBulkSMSRequestEntityIDRequiredValidation is returned when the EntityID is required but not provided.
	ErrSendBulkSMSRequestEntityIDRequiredValidation = govaliderrors.ValidationError{Reason: "field EntityID is required", Path: "SendBulkSMSRequest.EntityID", Type: "required"}
)

func ValidateSendBulkSMSRequest(t *SendBulkSMSRequest) error {
	if t == nil {
		return ErrNilSendBulkSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.SenderID == "" {
		err := ErrSendBulkSMSRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.MobileNumber == "" {
		err := ErrSendBulkSMSRequestMobileNumberRequiredValidation
		err.Value = t.MobileNumber
		errs = append(errs, err)
	}

	if t.MessageType == "" {
		err := ErrSendBulkSMSRequestMessageTypeRequiredValidation
		err.Value = t.MessageType
		errs = append(errs, err)
	}

	if t.MessageText == "" {
		err := ErrSendBulkSMSRequestMessageTextRequiredValidation
		err.Value = t.MessageText
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrSendBulkSMSRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if t.EntityID == "" {
		err := ErrSendBulkSMSRequestEntityIDRequiredValidation
		err.Value = t.EntityID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SendBulkSMSRequest)(nil)

func (t *SendBulkSMSRequest) Validate() error {
	return ValidateSendBulkSMSRequest(t)
}
