// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilValidateTestSMSRequest is returned when the ValidateTestSMSRequest is nil.
	ErrNilValidateTestSMSRequest = errors.New("input ValidateTestSMSRequest is nil")

	// ErrValidateTestSMSRequestReferenceIDRequiredValidation is returned when the ReferenceID is required but not provided.
	ErrValidateTestSMSRequestReferenceIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ReferenceID is required", Path: "ValidateTestSMSRequest.ReferenceID", Type: "required"}

	// ErrValidateTestSMSRequestTestStringRequiredValidation is returned when the TestString is required but not provided.
	ErrValidateTestSMSRequestTestStringRequiredValidation = govaliderrors.ValidationError{Reason: "field TestString is required", Path: "ValidateTestSMSRequest.TestString", Type: "required"}
)

func ValidateValidateTestSMSRequest(t *ValidateTestSMSRequest) error {
	if t == nil {
		return ErrNilValidateTestSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ReferenceID == "" {
		err := ErrValidateTestSMSRequestReferenceIDRequiredValidation
		err.Value = t.ReferenceID
		errs = append(errs, err)
	}

	if t.TestString == "" {
		err := ErrValidateTestSMSRequestTestStringRequiredValidation
		err.Value = t.TestString
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ValidateTestSMSRequest)(nil)

func (t *ValidateTestSMSRequest) Validate() error {
	return ValidateValidateTestSMSRequest(t)
}
