// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilFetchTemplateRequest is returned when the FetchTemplateRequest is nil.
	ErrNilFetchTemplateRequest = errors.New("input FetchTemplateRequest is nil")

	// ErrFetchTemplateRequestTemplateLocalIDRequiredValidation is returned when the TemplateLocalID is required but not provided.
	ErrFetchTemplateRequestTemplateLocalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateLocalID is required", Path: "FetchTemplateRequest.TemplateLocalID", Type: "required"}
)

func ValidateFetchTemplateRequest(t *FetchTemplateRequest) error {
	if t == nil {
		return ErrNilFetchTemplateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TemplateLocalID == 0 {
		err := ErrFetchTemplateRequestTemplateLocalIDRequiredValidation
		err.Value = t.TemplateLocalID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FetchTemplateRequest)(nil)

func (t *FetchTemplateRequest) Validate() error {
	return ValidateFetchTemplateRequest(t)
}
