// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilInitiateBulkSMSRequest is returned when the InitiateBulkSMSRequest is nil.
	ErrNilInitiateBulkSMSRequest = errors.New("input InitiateBulkSMSRequest is nil")

	// ErrInitiateBulkSMSRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrInitiateBulkSMSRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "InitiateBulkSMSRequest.ApplicationID", Type: "required"}

	// ErrInitiateBulkSMSRequestTemplateNameRequiredValidation is returned when the TemplateName is required but not provided.
	ErrInitiateBulkSMSRequestTemplateNameRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateName is required", Path: "InitiateBulkSMSRequest.TemplateName", Type: "required"}

	// ErrInitiateBulkSMSRequestMobileNoRequiredValidation is returned when the MobileNo is required but not provided.
	ErrInitiateBulkSMSRequestMobileNoRequiredValidation = govaliderrors.ValidationError{Reason: "field MobileNo is required", Path: "InitiateBulkSMSRequest.MobileNo", Type: "required"}

	// ErrInitiateBulkSMSRequestTestMessageRequiredValidation is returned when the TestMessage is required but not provided.
	ErrInitiateBulkSMSRequestTestMessageRequiredValidation = govaliderrors.ValidationError{Reason: "field TestMessage is required", Path: "InitiateBulkSMSRequest.TestMessage", Type: "required"}
)

func ValidateInitiateBulkSMSRequest(t *InitiateBulkSMSRequest) error {
	if t == nil {
		return ErrNilInitiateBulkSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrInitiateBulkSMSRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.TemplateName == "" {
		err := ErrInitiateBulkSMSRequestTemplateNameRequiredValidation
		err.Value = t.TemplateName
		errs = append(errs, err)
	}

	if t.MobileNo == "" {
		err := ErrInitiateBulkSMSRequestMobileNoRequiredValidation
		err.Value = t.MobileNo
		errs = append(errs, err)
	}

	if t.TestMessage == "" {
		err := ErrInitiateBulkSMSRequestTestMessageRequiredValidation
		err.Value = t.TestMessage
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*InitiateBulkSMSRequest)(nil)

func (t *InitiateBulkSMSRequest) Validate() error {
	return ValidateInitiateBulkSMSRequest(t)
}
