// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilAggregateSMSUsageReportRequest is returned when the AggregateSMSUsageReportRequest is nil.
	ErrNilAggregateSMSUsageReportRequest = errors.New("input AggregateSMSUsageReportRequest is nil")

	// ErrAggregateSMSUsageReportRequestFromDateRequiredValidation is returned when the FromDate is required but not provided.
	ErrAggregateSMSUsageReportRequestFromDateRequiredValidation = govaliderrors.ValidationError{Reason: "field FromDate is required", Path: "AggregateSMSUsageReportRequest.FromDate", Type: "required"}

	// ErrAggregateSMSUsageReportRequestToDateRequiredValidation is returned when the ToDate is required but not provided.
	ErrAggregateSMSUsageReportRequestToDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ToDate is required", Path: "AggregateSMSUsageReportRequest.ToDate", Type: "required"}

	// ErrAggregateSMSUsageReportRequestReportTypeRequiredValidation is returned when the ReportType is required but not provided.
	ErrAggregateSMSUsageReportRequestReportTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field ReportType is required", Path: "AggregateSMSUsageReportRequest.ReportType", Type: "required"}
)

func ValidateAggregateSMSUsageReportRequest(t *AggregateSMSUsageReportRequest) error {
	if t == nil {
		return ErrNilAggregateSMSUsageReportRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.FromDate == "" {
		err := ErrAggregateSMSUsageReportRequestFromDateRequiredValidation
		err.Value = t.FromDate
		errs = append(errs, err)
	}

	if t.ToDate == "" {
		err := ErrAggregateSMSUsageReportRequestToDateRequiredValidation
		err.Value = t.ToDate
		errs = append(errs, err)
	}

	if t.ReportType == 0 {
		err := ErrAggregateSMSUsageReportRequestReportTypeRequiredValidation
		err.Value = t.ReportType
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*AggregateSMSUsageReportRequest)(nil)

func (t *AggregateSMSUsageReportRequest) Validate() error {
	return ValidateAggregateSMSUsageReportRequest(t)
}
