// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilSentSMSStatusReportRequest is returned when the SentSMSStatusReportRequest is nil.
	ErrNilSentSMSStatusReportRequest = errors.New("input SentSMSStatusReportRequest is nil")

	// ErrSentSMSStatusReportRequestFromDateRequiredValidation is returned when the FromDate is required but not provided.
	ErrSentSMSStatusReportRequestFromDateRequiredValidation = govaliderrors.ValidationError{Reason: "field FromDate is required", Path: "SentSMSStatusReportRequest.FromDate", Type: "required"}

	// ErrSentSMSStatusReportRequestToDateRequiredValidation is returned when the ToDate is required but not provided.
	ErrSentSMSStatusReportRequestToDateRequiredValidation = govaliderrors.ValidationError{Reason: "field ToDate is required", Path: "SentSMSStatusReportRequest.ToDate", Type: "required"}
)

func ValidateSentSMSStatusReportRequest(t *SentSMSStatusReportRequest) error {
	if t == nil {
		return ErrNilSentSMSStatusReportRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.FromDate == "" {
		err := ErrSentSMSStatusReportRequestFromDateRequiredValidation
		err.Value = t.FromDate
		errs = append(errs, err)
	}

	if t.ToDate == "" {
		err := ErrSentSMSStatusReportRequestToDateRequiredValidation
		err.Value = t.ToDate
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*SentSMSStatusReportRequest)(nil)

func (t *SentSMSStatusReportRequest) Validate() error {
	return ValidateSentSMSStatusReportRequest(t)
}
