// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilFetchCDACSMSDeliveryStatusRequest is returned when the FetchCDACSMSDeliveryStatusRequest is nil.
	ErrNilFetchCDACSMSDeliveryStatusRequest = errors.New("input FetchCDACSMSDeliveryStatusRequest is nil")

	// ErrFetchCDACSMSDeliveryStatusRequestReferenceIDRequiredValidation is returned when the ReferenceID is required but not provided.
	ErrFetchCDACSMSDeliveryStatusRequestReferenceIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ReferenceID is required", Path: "FetchCDACSMSDeliveryStatusRequest.ReferenceID", Type: "required"}
)

func ValidateFetchCDACSMSDeliveryStatusRequest(t *FetchCDACSMSDeliveryStatusRequest) error {
	if t == nil {
		return ErrNilFetchCDACSMSDeliveryStatusRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ReferenceID == "" {
		err := ErrFetchCDACSMSDeliveryStatusRequestReferenceIDRequiredValidation
		err.Value = t.ReferenceID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FetchCDACSMSDeliveryStatusRequest)(nil)

func (t *FetchCDACSMSDeliveryStatusRequest) Validate() error {
	return ValidateFetchCDACSMSDeliveryStatusRequest(t)
}
