// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilToggleTemplateStatusRequest is returned when the ToggleTemplateStatusRequest is nil.
	ErrNilToggleTemplateStatusRequest = errors.New("input ToggleTemplateStatusRequest is nil")

	// ErrToggleTemplateStatusRequestTemplateLocalIDRequiredValidation is returned when the TemplateLocalID is required but not provided.
	ErrToggleTemplateStatusRequestTemplateLocalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateLocalID is required", Path: "ToggleTemplateStatusRequest.TemplateLocalID", Type: "required"}
)

func ValidateToggleTemplateStatusRequest(t *ToggleTemplateStatusRequest) error {
	if t == nil {
		return ErrNilToggleTemplateStatusRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TemplateLocalID == 0 {
		err := ErrToggleTemplateStatusRequestTemplateLocalIDRequiredValidation
		err.Value = t.TemplateLocalID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ToggleTemplateStatusRequest)(nil)

func (t *ToggleTemplateStatusRequest) Validate() error {
	return ValidateToggleTemplateStatusRequest(t)
}
