// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilFetchTemplateByApplicationRequest is returned when the FetchTemplateByApplicationRequest is nil.
	ErrNilFetchTemplateByApplicationRequest = errors.New("input FetchTemplateByApplicationRequest is nil")

	// ErrFetchTemplateByApplicationRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrFetchTemplateByApplicationRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "FetchTemplateByApplicationRequest.ApplicationID", Type: "required"}
)

func ValidateFetchTemplateByApplicationRequest(t *FetchTemplateByApplicationRequest) error {
	if t == nil {
		return ErrNilFetchTemplateByApplicationRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ApplicationID == "" {
		err := ErrFetchTemplateByApplicationRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FetchTemplateByApplicationRequest)(nil)

func (t *FetchTemplateByApplicationRequest) Validate() error {
	return ValidateFetchTemplateByApplicationRequest(t)
}
