// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilFetchMessageProviderRequest is returned when the FetchMessageProviderRequest is nil.
	ErrNilFetchMessageProviderRequest = errors.New("input FetchMessageProviderRequest is nil")

	// ErrFetchMessageProviderRequestProviderIDRequiredValidation is returned when the ProviderID is required but not provided.
	ErrFetchMessageProviderRequestProviderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderID is required", Path: "FetchMessageProviderRequest.ProviderID", Type: "required"}
)

func ValidateFetchMessageProviderRequest(t *FetchMessageProviderRequest) error {
	if t == nil {
		return ErrNilFetchMessageProviderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProviderID == 0 {
		err := ErrFetchMessageProviderRequestProviderIDRequiredValidation
		err.Value = t.ProviderID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*FetchMessageProviderRequest)(nil)

func (t *FetchMessageProviderRequest) Validate() error {
	return ValidateFetchMessageProviderRequest(t)
}
