// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilUpdateTemplateRequest is returned when the UpdateTemplateRequest is nil.
	ErrNilUpdateTemplateRequest = errors.New("input UpdateTemplateRequest is nil")

	// ErrUpdateTemplateRequestTemplateLocalIDRequiredValidation is returned when the TemplateLocalID is required but not provided.
	ErrUpdateTemplateRequestTemplateLocalIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateLocalID is required", Path: "UpdateTemplateRequest.TemplateLocalID", Type: "required"}

	// ErrUpdateTemplateRequestApplicationIDRequiredValidation is returned when the ApplicationID is required but not provided.
	ErrUpdateTemplateRequestApplicationIDRequiredValidation = govaliderrors.ValidationError{Reason: "field ApplicationID is required", Path: "UpdateTemplateRequest.ApplicationID", Type: "required"}

	// ErrUpdateTemplateRequestTemplateNameRequiredValidation is returned when the TemplateName is required but not provided.
	ErrUpdateTemplateRequestTemplateNameRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateName is required", Path: "UpdateTemplateRequest.TemplateName", Type: "required"}

	// ErrUpdateTemplateRequestTemplateFormatRequiredValidation is returned when the TemplateFormat is required but not provided.
	ErrUpdateTemplateRequestTemplateFormatRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateFormat is required", Path: "UpdateTemplateRequest.TemplateFormat", Type: "required"}

	// ErrUpdateTemplateRequestSenderIDRequiredValidation is returned when the SenderID is required but not provided.
	ErrUpdateTemplateRequestSenderIDRequiredValidation = govaliderrors.ValidationError{Reason: "field SenderID is required", Path: "UpdateTemplateRequest.SenderID", Type: "required"}

	// ErrUpdateTemplateRequestTemplateIDRequiredValidation is returned when the TemplateID is required but not provided.
	ErrUpdateTemplateRequestTemplateIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TemplateID is required", Path: "UpdateTemplateRequest.TemplateID", Type: "required"}

	// ErrUpdateTemplateRequestGatewayRequiredValidation is returned when the Gateway is required but not provided.
	ErrUpdateTemplateRequestGatewayRequiredValidation = govaliderrors.ValidationError{Reason: "field Gateway is required", Path: "UpdateTemplateRequest.Gateway", Type: "required"}

	// ErrUpdateTemplateRequestMessageTypeRequiredValidation is returned when the MessageType is required but not provided.
	ErrUpdateTemplateRequestMessageTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MessageType is required", Path: "UpdateTemplateRequest.MessageType", Type: "required"}

	// ErrUpdateTemplateRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrUpdateTemplateRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "UpdateTemplateRequest.Status", Type: "required"}
)

func ValidateUpdateTemplateRequest(t *UpdateTemplateRequest) error {
	if t == nil {
		return ErrNilUpdateTemplateRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.TemplateLocalID == 0 {
		err := ErrUpdateTemplateRequestTemplateLocalIDRequiredValidation
		err.Value = t.TemplateLocalID
		errs = append(errs, err)
	}

	if t.ApplicationID == "" {
		err := ErrUpdateTemplateRequestApplicationIDRequiredValidation
		err.Value = t.ApplicationID
		errs = append(errs, err)
	}

	if t.TemplateName == "" {
		err := ErrUpdateTemplateRequestTemplateNameRequiredValidation
		err.Value = t.TemplateName
		errs = append(errs, err)
	}

	if t.TemplateFormat == "" {
		err := ErrUpdateTemplateRequestTemplateFormatRequiredValidation
		err.Value = t.TemplateFormat
		errs = append(errs, err)
	}

	if t.SenderID == "" {
		err := ErrUpdateTemplateRequestSenderIDRequiredValidation
		err.Value = t.SenderID
		errs = append(errs, err)
	}

	if t.TemplateID == "" {
		err := ErrUpdateTemplateRequestTemplateIDRequiredValidation
		err.Value = t.TemplateID
		errs = append(errs, err)
	}

	if t.Gateway == "" {
		err := ErrUpdateTemplateRequestGatewayRequiredValidation
		err.Value = t.Gateway
		errs = append(errs, err)
	}

	if t.MessageType == "" {
		err := ErrUpdateTemplateRequestMessageTypeRequiredValidation
		err.Value = t.MessageType
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrUpdateTemplateRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UpdateTemplateRequest)(nil)

func (t *UpdateTemplateRequest) Validate() error {
	return ValidateUpdateTemplateRequest(t)
}
