// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilCreateMessageProviderRequest is returned when the CreateMessageProviderRequest is nil.
	ErrNilCreateMessageProviderRequest = errors.New("input CreateMessageProviderRequest is nil")

	// ErrCreateMessageProviderRequestProviderNameRequiredValidation is returned when the ProviderName is required but not provided.
	ErrCreateMessageProviderRequestProviderNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ProviderName is required", Path: "CreateMessageProviderRequest.ProviderName", Type: "required"}

	// ErrCreateMessageProviderRequestShortNameRequiredValidation is returned when the ShortName is required but not provided.
	ErrCreateMessageProviderRequestShortNameRequiredValidation = govaliderrors.ValidationError{Reason: "field ShortName is required", Path: "CreateMessageProviderRequest.ShortName", Type: "required"}

	// ErrCreateMessageProviderRequestServicesRequiredValidation is returned when the Services is required but not provided.
	ErrCreateMessageProviderRequestServicesRequiredValidation = govaliderrors.ValidationError{Reason: "field Services is required", Path: "CreateMessageProviderRequest.Services", Type: "required"}

	// ErrCreateMessageProviderRequestStatusRequiredValidation is returned when the Status is required but not provided.
	ErrCreateMessageProviderRequestStatusRequiredValidation = govaliderrors.ValidationError{Reason: "field Status is required", Path: "CreateMessageProviderRequest.Status", Type: "required"}
)

func ValidateCreateMessageProviderRequest(t *CreateMessageProviderRequest) error {
	if t == nil {
		return ErrNilCreateMessageProviderRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.ProviderName == "" {
		err := ErrCreateMessageProviderRequestProviderNameRequiredValidation
		err.Value = t.ProviderName
		errs = append(errs, err)
	}

	if t.ShortName == "" {
		err := ErrCreateMessageProviderRequestShortNameRequiredValidation
		err.Value = t.ShortName
		errs = append(errs, err)
	}

	if t.Services == "" {
		err := ErrCreateMessageProviderRequestServicesRequiredValidation
		err.Value = t.Services
		errs = append(errs, err)
	}

	if t.Status == false {
		err := ErrCreateMessageProviderRequestStatusRequiredValidation
		err.Value = t.Status
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateMessageProviderRequest)(nil)

func (t *CreateMessageProviderRequest) Validate() error {
	return ValidateCreateMessageProviderRequest(t)
}
