// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
)

var (
	// ErrNilCreateTestSMSRequest is returned when the CreateTestSMSRequest is nil.
	ErrNilCreateTestSMSRequest = errors.New("input CreateTestSMSRequest is nil")

	// ErrCreateTestSMSRequestMobileNumberRequiredValidation is returned when the MobileNumber is required but not provided.
	ErrCreateTestSMSRequestMobileNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field MobileNumber is required", Path: "CreateTestSMSRequest.MobileNumber", Type: "required"}
)

func ValidateCreateTestSMSRequest(t *CreateTestSMSRequest) error {
	if t == nil {
		return ErrNilCreateTestSMSRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.MobileNumber == "" {
		err := ErrCreateTestSMSRequestMobileNumberRequiredValidation
		err.Value = t.MobileNumber
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*CreateTestSMSRequest)(nil)

func (t *CreateTestSMSRequest) Validate() error {
	return ValidateCreateTestSMSRequest(t)
}
