// Code generated by govalid; DO NOT EDIT.
package models

import (
	"errors"

	"github.com/templatedop/govalid"
	govaliderrors "github.com/templatedop/govalid/validation/errors"
	"github.com/templatedop/govalid/validation/validationhelper"
)

var (
	// ErrNilTestStruct is returned when the TestStruct is nil.
	ErrNilTestStruct = errors.New("input TestStruct is nil")

	// ErrTestStructNameRequiredValidation is returned when the Name is required but not provided.
	ErrTestStructNameRequiredValidation = govaliderrors.ValidationError{Reason: "field Name is required", Path: "TestStruct.Name", Type: "required"}

	// ErrTestStructEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrTestStructEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "TestStruct.Email", Type: "email"}

	// ErrTestStructAgeGTValidation is the error returned when the value of the field is less than the 0.
	ErrTestStructAgeGTValidation = govaliderrors.ValidationError{Reason: "field Age must be greater than 0", Path: "TestStruct.Age", Type: "gt"}

	// ErrTestStructAgeLTValidation is the error returned when the value of the field is greater than the 150.
	ErrTestStructAgeLTValidation = govaliderrors.ValidationError{Reason: "field Age must be less than 150", Path: "TestStruct.Age", Type: "lt"}
)

func ValidateTestStruct(t *TestStruct) error {
	if t == nil {
		return ErrNilTestStruct
	}

	var errs govaliderrors.ValidationErrors

	if t.Name == "" {
		err := ErrTestStructNameRequiredValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if !validationhelper.IsValidEmail(t.Email) {
		err := ErrTestStructEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if !(t.Age > 0) {
		err := ErrTestStructAgeGTValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if !(t.Age < 150) {
		err := ErrTestStructAgeLTValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*TestStruct)(nil)

func (t *TestStruct) Validate() error {
	return ValidateTestStruct(t)
}
